---
abstract: 'A Client for the Firefox Sync Server'
author:
  - 'Robin Schroeder <schrorg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Firefox-Sync-Client
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::Rijndael: 0
  Digest::SHA: 0
  JSON: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  MIME::Base32: 0
  MIME::Base64: 0
  Storable: 0
version: 0.04
